name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: ./
        id: vcpkg
        with: { committish: 7e3dcf74e37034eea358934a90a11d618520e139 }

      - run: |
          printf "Cache hit: '%s'\n" "${{ steps.vcpkg.outputs.cache-hit }}"
          $VCPKG_ROOT/vcpkg version
