name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: ./
        id: vcpkg
        with: { committish: 934a99dc13cabb330824ae1a5ab4a53a9acc5a49 }

      - run: |
          printf "Cache hit: '%s'\n" "${{ steps.vcpkg.outputs.cache-hit }}"
          $VCPKG_ROOT/vcpkg version
